using MySqlConnector;
using SkyLab.Web.Models;
namespace SkyLab.Web.Services;
public sealed class UserService(IConfiguration configuration)
{
 private static readonly LookupOption[] UserTypes=[new(1,"Assistenza"),new(2,"Amministratore del sistema"),new(3,"Utente normale"),new(4,"Operatore esterno")];
 private static readonly LookupOption[] Qualifications=[new(1,"Titolare azienda"),new(2,"Dirigente azienda"),new(3,"Impiegato amministrativo"),new(4,"Impiegato tecnico"),new(5,"Agente"),new(6,"Cassiere"),new(7,"Esterno all'azienda")];
 private string ConnectionString{get{var value=configuration.GetConnectionString("SkyLabDb")??configuration.GetConnectionString("MicronoteDb")??throw new InvalidOperationException("Connessione MySQL SkyLab non configurata.");return new MySqlConnectionStringBuilder(value){Database="skylab_0001",SslMode=MySqlSslMode.None}.ConnectionString;}}
 public async Task<IReadOnlyList<UserListItem>> SearchAsync(string? search,CancellationToken ct=default){const string sql="SELECT Codice,COALESCE(Cognome,''),COALESCE(Nome,''),COALESCE(Username,''),COALESCE(Citta,''),COALESCE(Telefono,''),COALESCE(Email,''),COALESCE(Bloccato,0),COALESCE(Attivo,1),COALESCE(Tipo,0) FROM Utenti WHERE @search='' OR Cognome LIKE CONCAT('%',@search,'%') OR Nome LIKE CONCAT('%',@search,'%') OR Username LIKE CONCAT('%',@search,'%') ORDER BY Codice";var items=new List<UserListItem>();await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new MySqlCommand(sql,cn);cmd.Parameters.AddWithValue("@search",search?.Trim()??"");await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var type=r.GetInt32(9);items.Add(new(r.GetInt32(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetBoolean(7),r.GetBoolean(8),type,UserTypes.FirstOrDefault(x=>x.Code==type)?.Description??""));}return items;}
 public async Task<UserEditModel?> GetAsync(int code,CancellationToken ct=default){const string sql="SELECT Codice,COALESCE(Cognome,''),COALESCE(Nome,''),COALESCE(Citta,''),COALESCE(Indirizzo,''),COALESCE(CodFi,''),COALESCE(Telefono,''),COALESCE(Email,''),COALESCE(Username,''),COALESCE(Passwd,''),COALESCE(Tipo,0),COALESCE(Qualifica,0),COALESCE(PuntoV,0),COALESCE(Sesso,''),COALESCE(Attivo,1),COALESCE(Bloccato,0) FROM Utenti WHERE Codice=@code";await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new MySqlCommand(sql,cn);cmd.Parameters.AddWithValue("@code",code);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;return new(){Code=r.GetInt32(0),LastName=r.GetString(1),FirstName=r.GetString(2),City=r.GetString(3),Address=r.GetString(4),TaxCode=r.GetString(5),Phone=r.GetString(6),Email=r.GetString(7),UserName=r.GetString(8),Password=r.GetString(9),TypeCode=NullZero(r.GetInt32(10)),QualificationCode=NullZero(r.GetInt32(11)),LocationCode=NullZero(r.GetInt32(12)),Gender=r.GetString(13),IsActive=r.GetBoolean(14),IsLocked=r.GetBoolean(15)};}
 public async Task<int> NextCodeAsync(CancellationToken ct=default){await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new MySqlCommand("SELECT COALESCE(MAX(Codice),0)+1 FROM Utenti",cn);return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}
 public async Task<UserLookups> GetLookupsAsync(CancellationToken ct=default){var locations=new List<LookupOption>();await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new MySqlCommand("SELECT Codice,COALESCE(NULLIF(NomeBreve,''),Nome,'') FROM UnitaLocali WHERE COALESCE(Attivo,0)<>0 ORDER BY NomeBreve,Nome",cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))locations.Add(new(r.GetInt32(0),r.GetString(1)));return new(locations,UserTypes,Qualifications);}
 public async Task<IReadOnlyList<string>> GetMobileLoginUsersAsync(CancellationToken ct=default){var users=new List<string>();await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var cmd=new MySqlCommand("SELECT TRIM(Username) FROM Utenti WHERE COALESCE(Attivo,0)<>0 AND COALESCE(Qualifica,0) IN (1,4) AND NULLIF(TRIM(Username),'') IS NOT NULL ORDER BY Username",cn);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))users.Add(r.GetString(0));return users;}
 public async Task<bool> VerifyMobileLoginAsync(string username,string password,CancellationToken ct=default){await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);const string sql="SELECT COUNT(*) FROM Utenti WHERE COALESCE(Attivo,0)<>0 AND COALESCE(Qualifica,0) IN (1,4) AND Username=@username AND Passwd=@password";await using var cmd=new MySqlCommand(sql,cn);cmd.Parameters.AddWithValue("@username",username.Trim());cmd.Parameters.AddWithValue("@password",password);return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct))==1;}
 public async Task<int> SaveAsync(UserEditModel u,CancellationToken ct=default){await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using var tx=await cn.BeginTransactionAsync(ct);await using(var dup=new MySqlCommand("SELECT COUNT(*) FROM Utenti WHERE Username=@name AND Codice<>@code",cn,tx)){dup.Parameters.AddWithValue("@name",u.UserName.Trim());dup.Parameters.AddWithValue("@code",u.Code);if(Convert.ToInt32(await dup.ExecuteScalarAsync(ct))>0)throw new InvalidOperationException("Username già presente.");}if(u.Code==0){await using var next=new MySqlCommand("SELECT COALESCE(MAX(Codice),0)+1 FROM Utenti FOR UPDATE",cn,tx);u.Code=Convert.ToInt32(await next.ExecuteScalarAsync(ct));}const string sql="INSERT INTO Utenti(Codice,Cognome,Nome,Citta,Indirizzo,CodFi,Telefono,Email,Attivo,Username,Passwd,Bloccato,Tipo,Qualifica,PuntoV,Sesso) VALUES(@code,@last,@first,@city,@address,@tax,@phone,@email,@active,@username,@password,@locked,@type,@qualification,@location,@gender) ON DUPLICATE KEY UPDATE Cognome=VALUES(Cognome),Nome=VALUES(Nome),Citta=VALUES(Citta),Indirizzo=VALUES(Indirizzo),CodFi=VALUES(CodFi),Telefono=VALUES(Telefono),Email=VALUES(Email),Attivo=VALUES(Attivo),Username=VALUES(Username),Passwd=VALUES(Passwd),Bloccato=VALUES(Bloccato),Tipo=VALUES(Tipo),Qualifica=VALUES(Qualifica),PuntoV=VALUES(PuntoV),Sesso=VALUES(Sesso)";await using var cmd=new MySqlCommand(sql,cn,tx);cmd.Parameters.AddWithValue("@code",u.Code);cmd.Parameters.AddWithValue("@last",u.LastName.Trim());cmd.Parameters.AddWithValue("@first",u.FirstName.Trim());cmd.Parameters.AddWithValue("@city",Db(u.City));cmd.Parameters.AddWithValue("@address",Db(u.Address));cmd.Parameters.AddWithValue("@tax",Db(u.TaxCode?.ToUpperInvariant()));cmd.Parameters.AddWithValue("@phone",Db(u.Phone));cmd.Parameters.AddWithValue("@email",Db(u.Email));cmd.Parameters.AddWithValue("@active",u.IsActive);cmd.Parameters.AddWithValue("@username",u.UserName.Trim());cmd.Parameters.AddWithValue("@password",u.Password.Trim());cmd.Parameters.AddWithValue("@locked",u.IsLocked);cmd.Parameters.AddWithValue("@type",u.TypeCode??0);cmd.Parameters.AddWithValue("@qualification",u.QualificationCode??0);cmd.Parameters.AddWithValue("@location",u.LocationCode??0);cmd.Parameters.AddWithValue("@gender",Db(u.Gender));await cmd.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return u.Code;}
 public async Task<UserDeleteResult> DeleteAsync(int code,CancellationToken ct=default){await using var cn=new MySqlConnection(ConnectionString);await cn.OpenAsync(ct);await using(var check=new MySqlCommand("SELECT COALESCE(Tipo,0) FROM Utenti WHERE Codice=@code",cn)){check.Parameters.AddWithValue("@code",code);var value=await check.ExecuteScalarAsync(ct);if(value is null)return new(false,"Utente non trovato.");if(Convert.ToInt32(value)==1)return new(false,"L'utente di assistenza non può essere eliminato.");}await using(var linked=new MySqlCommand("SELECT COUNT(*) FROM Attivita WHERE Utente=@code",cn)){linked.Parameters.AddWithValue("@code",code);if(Convert.ToInt32(await linked.ExecuteScalarAsync(ct))>0)return new(false,"L'utente non può essere eliminato: esistono attività collegate.");}await using var del=new MySqlCommand("DELETE FROM Utenti WHERE Codice=@code",cn);del.Parameters.AddWithValue("@code",code);return await del.ExecuteNonQueryAsync(ct)==1?new(true,"Utente eliminato."):new(false,"Utente non trovato.");}
 private static int? NullZero(int value)=>value==0?null:value; private static object Db(string? value)=>string.IsNullOrWhiteSpace(value)?DBNull.Value:value.Trim();
}
