-- SkyLabdb: allineamento della tabella banche al modello applicativo MicroFish.
ALTER TABLE banche
  MODIFY COLUMN Codice INT NOT NULL FIRST,
  MODIFY COLUMN Nome VARCHAR(100) NOT NULL AFTER Codice,
  MODIFY COLUMN Agenzia VARCHAR(50) NULL DEFAULT '' AFTER Nome,
  MODIFY COLUMN Abi VARCHAR(5) NULL DEFAULT '' AFTER Agenzia,
  MODIFY COLUMN Cab VARCHAR(5) NULL DEFAULT '' AFTER Abi,
  MODIFY COLUMN Conto VARCHAR(25) NULL DEFAULT '' AFTER Cab,
  MODIFY COLUMN Iban VARCHAR(50) NULL DEFAULT '' AFTER Conto,
  CHANGE COLUMN Telefono1 Telefono VARCHAR(30) NULL DEFAULT '' AFTER Iban,
  CHANGE COLUMN Telefono2 Cellulare VARCHAR(30) NULL DEFAULT NULL AFTER Telefono,
  MODIFY COLUMN Email VARCHAR(100) NULL DEFAULT '' AFTER Cellulare,
  MODIFY COLUMN SitoWeb VARCHAR(100) NULL DEFAULT '' AFTER Email,
  ADD COLUMN Swift VARCHAR(12) NULL DEFAULT '' AFTER SitoWeb,
  ADD COLUMN Sia VARCHAR(10) NULL DEFAULT '' AFTER Swift,
  MODIFY COLUMN Notes VARCHAR(255) NULL DEFAULT '' AFTER Sia,
  ADD CONSTRAINT PK_banche PRIMARY KEY (Codice),
  ADD INDEX IX_banche_Nome (Nome);
