-- SkyLabdb: completamento struttura padre-figlio carico/caricorg.
DELETE r
FROM caricorg r
LEFT JOIN carico c ON c.ID=r.ID
WHERE c.ID IS NULL;

UPDATE carico SET
  Anno=COALESCE(Anno,0), Codice=COALESCE(Codice,0), Causale=COALESCE(Causale,0),
  TipoDoc=COALESCE(TipoDoc,0), Ditta=COALESCE(Ditta,0), ULocale=COALESCE(ULocale,0),
  Totale=COALESCE(Totale,0), Ordine=COALESCE(Ordine,0);

UPDATE caricorg SET
  Anno=COALESCE(Anno,0), Codice=COALESCE(Codice,0), Riga=COALESCE(Riga,0),
  Articolo=COALESCE(Articolo,''), Quantita=COALESCE(Quantita,0), Prezzo=COALESCE(Prezzo,0),
  Sconto=COALESCE(Sconto,0), PrNetto=COALESCE(PrNetto,0), Importo=COALESCE(Importo,0);

ALTER TABLE carico
  MODIFY COLUMN Anno SMALLINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Codice INT NOT NULL DEFAULT 0,
  MODIFY COLUMN Causale SMALLINT NOT NULL DEFAULT 0,
  MODIFY COLUMN TipoDoc TINYINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Ditta INT NOT NULL DEFAULT 0,
  MODIFY COLUMN ULocale SMALLINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Totale DECIMAL(12,2) NOT NULL DEFAULT 0,
  MODIFY COLUMN Ordine INT NOT NULL DEFAULT 0,
  ADD CONSTRAINT UX_carico_Anno_Codice UNIQUE (Anno, Codice),
  ADD INDEX IX_carico_DataDoc (DataDoc),
  ADD INDEX IX_carico_Ditta_DataDoc (Ditta, DataDoc),
  ADD INDEX IX_carico_Causale_DataDoc (Causale, DataDoc);

ALTER TABLE caricorg
  MODIFY COLUMN ID INT NOT NULL,
  MODIFY COLUMN Anno SMALLINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Codice INT NOT NULL DEFAULT 0,
  MODIFY COLUMN Riga SMALLINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Articolo VARCHAR(30) NOT NULL,
  MODIFY COLUMN Quantita DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Prezzo DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Sconto DECIMAL(5,2) NOT NULL DEFAULT 0,
  MODIFY COLUMN PrNetto DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Importo DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD CONSTRAINT PK_caricorg PRIMARY KEY (ID, Riga),
  ADD INDEX IX_caricorg_Anno_Codice_Riga (Anno, Codice, Riga),
  ADD INDEX IX_caricorg_Articolo (Articolo),
  ADD CONSTRAINT FK_caricorg_carico FOREIGN KEY (ID) REFERENCES carico (ID)
    ON UPDATE RESTRICT ON DELETE CASCADE,
  ADD CONSTRAINT FK_caricorg_articoli FOREIGN KEY (Articolo) REFERENCES articoli (Codice)
    ON UPDATE CASCADE ON DELETE RESTRICT;
