CREATE TABLE IF NOT EXISTS ddt_legacy_backup LIKE ddt;
INSERT INTO ddt_legacy_backup SELECT * FROM ddt
WHERE NOT EXISTS (SELECT 1 FROM ddt_legacy_backup LIMIT 1);

CREATE TABLE IF NOT EXISTS ddtrg_legacy_backup LIKE ddtrg;
INSERT INTO ddtrg_legacy_backup SELECT * FROM ddtrg
WHERE NOT EXISTS (SELECT 1 FROM ddtrg_legacy_backup LIMIT 1);

DELETE r
FROM ddtrg r
LEFT JOIN ddt h ON h.Anno=r.Anno AND h.Codice=r.Codice
WHERE h.Codice IS NULL;

ALTER TABLE ddt
  ADD COLUMN _NewID INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE ddt
  DROP COLUMN ID,
  CHANGE COLUMN _NewID ID INT NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN Anno SMALLINT NOT NULL,
  MODIFY COLUMN Codice INT NOT NULL,
  ADD CONSTRAINT UQ_ddt_Anno_Codice UNIQUE (Anno,Codice),
  ADD INDEX IX_ddt_DataDoc (DataDoc),
  ADD INDEX IX_ddt_CliFor_Ditta (CliFor,Ditta),
  ADD INDEX IX_ddt_IdFattura (IdFattura),
  ADD INDEX IX_ddt_IdOrdine (IdOrdine);

ALTER TABLE ddtrg
  ADD COLUMN ID INT NULL FIRST;

UPDATE ddtrg r
JOIN ddt h ON h.Anno=r.Anno AND h.Codice=r.Codice
SET r.ID=h.ID;

ALTER TABLE ddtrg
  MODIFY COLUMN ID INT NOT NULL,
  MODIFY COLUMN Anno SMALLINT NOT NULL,
  MODIFY COLUMN Settore TINYINT NOT NULL DEFAULT 0,
  MODIFY COLUMN Codice INT NOT NULL,
  MODIFY COLUMN Riga SMALLINT NOT NULL,
  MODIFY COLUMN Quantita DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Peso DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Prezzo DECIMAL(12,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Sconto DECIMAL(7,3) NOT NULL DEFAULT 0,
  MODIFY COLUMN Importo DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD CONSTRAINT PK_ddtrg PRIMARY KEY (ID,Riga),
  ADD INDEX IX_ddtrg_Anno_Settore_Codice_Riga (Anno,Settore,Codice,Riga),
  ADD INDEX IX_ddtrg_Articolo (Articolo),
  ADD CONSTRAINT FK_ddtrg_ddt FOREIGN KEY (ID) REFERENCES ddt(ID)
    ON UPDATE RESTRICT ON DELETE CASCADE;
