ALTER TABLE scadenze
  ADD COLUMN ID INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY COLUMN Anno SMALLINT NOT NULL,
  MODIFY COLUMN Settore TINYINT NOT NULL,
  MODIFY COLUMN Codice INT NOT NULL,
  MODIFY COLUMN Numero SMALLINT NOT NULL,
  ADD CONSTRAINT PK_scadenze PRIMARY KEY (ID),
  ADD CONSTRAINT UX_scadenze_Mnemonica UNIQUE (Anno, Settore, Codice, Numero);
