CREATE TABLE ImpegniLavoro (
  ID INT NOT NULL AUTO_INCREMENT,
  Cliente_ID INT NOT NULL,
  MacchinaCli_ID INT NULL,
  Origine CHAR(1) NOT NULL DEFAULT 'P' COMMENT 'P=programmata, S=straordinaria, N=nuovo lavoro',
  DataScadenzaOrigine DATE NULL,
  DataAcquisizione DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DataIntervento DATE NULL,
  OraIntervento TIME NULL,
  Stato CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A=acquisito, P=pianificato, T=trasformato, X=annullato',
  Lavoro_ID INT NULL,
  Descrizione VARCHAR(255) NULL,
  Note VARCHAR(500) NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_ImpegniLavoro_Lavoro (Lavoro_ID),
  KEY IX_ImpegniLavoro_Stato_Data (Stato, DataIntervento),
  KEY IX_ImpegniLavoro_Cliente (Cliente_ID, Stato),
  KEY IX_ImpegniLavoro_Macchina (MacchinaCli_ID, DataScadenzaOrigine),
  CONSTRAINT FK_ImpegniLavoro_Clienti FOREIGN KEY (Cliente_ID) REFERENCES Clienti(Codice),
  CONSTRAINT FK_ImpegniLavoro_MacchineCli FOREIGN KEY (MacchinaCli_ID) REFERENCES MacchineCli(ID),
  CONSTRAINT FK_ImpegniLavoro_Lavori FOREIGN KEY (Lavoro_ID) REFERENCES Lavori(ID),
  CONSTRAINT CK_ImpegniLavoro_Origine CHECK (Origine IN ('P','S','N')),
  CONSTRAINT CK_ImpegniLavoro_Stato CHECK (Stato IN ('A','P','T','X'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
