using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.AspNetCore.Mvc.Rendering;using SkyLab.Web.Models;using SkyLab.Web.Services;
namespace SkyLab.Web.Pages.Fornitori;
public sealed class EditModel(SupplierService service):PageModel
{
 [BindProperty] public SupplierEditModel Fornitore{get;set;}=new(); public IReadOnlyList<SelectListItem> Countries{get;private set;}=[];public IReadOnlyList<SelectListItem> Payments{get;private set;}=[];public IReadOnlyList<SelectListItem> Banks{get;private set;}=[];public IReadOnlyList<SelectListItem> LocalUnits{get;private set;}=[];public IReadOnlyList<SelectListItem> Accounts{get;private set;}=[];
 public int Azione{get;private set;} public string ReturnTo{get;private set;}="";
 public async Task<IActionResult> OnGetAsync(int? id,int? azione,string? returnTo,string? name,string? vat,string? fiscalCode,string? address,string? city,string? postalCode,string? province,string? phone,string? email,string? certifiedEmail,CancellationToken ct){Azione=azione??0;ReturnTo=returnTo??"";if(id.HasValue){Fornitore=await service.GetAsync(id.Value,ct)??new();if(Fornitore.Code==0)return NotFound();}else{Fornitore.Name=name?.Trim()??"";Fornitore.VatNumber=vat?.Trim()??"";Fornitore.TaxCode=fiscalCode?.Trim()??"";Fornitore.Street=address?.Trim()??"";Fornitore.City=city?.Trim()??"";Fornitore.PostalCode=postalCode?.Trim()??"";Fornitore.Province=province?.Trim().ToUpperInvariant()??"";Fornitore.Phone1=phone?.Trim()??"";Fornitore.Email=email?.Trim()??"";Fornitore.CertifiedEmail=certifiedEmail?.Trim()??"";}await LoadAsync(ct);return Page();}
 public async Task<IActionResult> OnPostAsync(int? azione,string? returnTo,CancellationToken ct){Azione=azione??0;ReturnTo=returnTo??"";if(!ModelState.IsValid){if(WantsJson())return ValidationJson();await LoadAsync(ct);return Page();}try{var code=await service.SaveAsync(Fornitore,ct);Fornitore.Code=code;if(IsPurchaseInvoiceXmlCall()){return new JsonResult(new{success=true,code,name=Fornitore.Name});}if(WantsJson()){return new JsonResult(new{success=true,redirectUrl=Url.Page("Index")});}TempData["Message"]="Fornitore salvato.";return RedirectToPage("Index");}catch(Exception ex){if(WantsJson()){return new JsonResult(new{success=false,message=ex.Message});}ModelState.AddModelError("",ex.Message);await LoadAsync(ct);return Page();}}
 private bool IsPurchaseInvoiceXmlCall()=>Azione==102&&string.Equals(ReturnTo,"purchaseInvoiceXml",StringComparison.OrdinalIgnoreCase);
 private bool WantsJson()=>IsPurchaseInvoiceXmlCall()||Request.Headers.Accept.Any(x=>x?.Contains("application/json",StringComparison.OrdinalIgnoreCase)==true)||string.Equals(Request.Headers.XRequestedWith,"XMLHttpRequest",StringComparison.OrdinalIgnoreCase);
 private JsonResult ValidationJson(){var message=ModelState.Values.SelectMany(v=>v.Errors).Select(e=>e.ErrorMessage).FirstOrDefault(m=>!string.IsNullOrWhiteSpace(m))??"Dati fornitore non validi.";return new JsonResult(new{success=false,message});}
 private async Task LoadAsync(CancellationToken ct){Countries=Map(await service.CountriesAsync(ct));Payments=Map(await service.PaymentsAsync(ct));Banks=Map(await service.BanksAsync(ct));LocalUnits=Map(await service.LocalUnitsAsync(ct));Accounts=Map(await service.AccountsAsync(ct));}private static IReadOnlyList<SelectListItem> Map(IReadOnlyList<SupplierOption> x)=>x.Select(v=>new SelectListItem(v.Label,v.Id.ToString())).ToList();
}
