using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.Mvc.RazorPages; using Microsoft.AspNetCore.Mvc.Rendering; using MySqlConnector; using SkyLab.Web.Models; using SkyLab.Web.Services;
namespace SkyLab.Web.Pages.Utenti;
public sealed class EditModel(UserService service):PageModel
{
 [BindProperty] public UserEditModel AppUser{get;set;}=new(); [BindProperty] public int Azione{get;set;}=FormAzione.Inserimento; public bool IsNew=>FormAzione.IsInserimento(Azione); public int DisplayCode{get;private set;} public SelectList Locations{get;private set;}=Empty(); public SelectList Types{get;private set;}=Empty(); public SelectList Qualifications{get;private set;}=Empty();
 public async Task<IActionResult> OnGetAsync(int? code,int? azione,CancellationToken ct){Azione=azione is>0?FormAzione.Normalize(azione.Value,FormAzione.ForRecord(code.HasValue)):FormAzione.ForRecord(code.HasValue);if(code.HasValue){var found=await service.GetAsync(code.Value,ct);if(found is null)return NotFound();AppUser=found;}else DisplayCode=await service.NextCodeAsync(ct);await LoadAsync(ct);return Page();}
 public async Task<IActionResult> OnPostAsync(CancellationToken ct){Azione=FormAzione.Normalize(Azione,FormAzione.ForRecord(AppUser.Code>0));Normalize();if(!ModelState.IsValid){if(AppUser.Code==0)DisplayCode=await service.NextCodeAsync(ct);await LoadAsync(ct);return Page();}try{await service.SaveAsync(AppUser,ct);}catch(InvalidOperationException ex){ModelState.AddModelError("",ex.Message);await LoadAsync(ct);return Page();}catch(MySqlException ex){ModelState.AddModelError("",$"Salvataggio non riuscito: {ex.Message}");await LoadAsync(ct);return Page();}return RedirectToPage("./Index");}
 private async Task LoadAsync(CancellationToken ct){var x=await service.GetLookupsAsync(ct);Locations=Select(x.Locations);Types=Select(x.Types);Qualifications=Select(x.Qualifications);} private void Normalize(){AppUser.LastName=AppUser.LastName?.Trim()??"";AppUser.FirstName=AppUser.FirstName?.Trim()??"";AppUser.UserName=AppUser.UserName?.Trim()??"";AppUser.Password=AppUser.Password?.Trim()??"";AppUser.City=AppUser.City?.Trim();AppUser.Address=AppUser.Address?.Trim();AppUser.TaxCode=AppUser.TaxCode?.Trim().ToUpperInvariant();AppUser.Phone=AppUser.Phone?.Trim();AppUser.Email=AppUser.Email?.Trim();} private static SelectList Select(IReadOnlyList<LookupOption> x)=>new(x,nameof(LookupOption.Code),nameof(LookupOption.Description)); private static SelectList Empty()=>new(Array.Empty<LookupOption>());
}
